### ISSUE TITLE
init2-WIFI.lua error

### ISSUE THREAD

**Issue by kskenyon** [BLavery/esuite-lua#1]
> PANIC: unprotected error in call to Lua API (init2-WIFI.lua:16: 'end' expected (to close 'function' at line 14) near '<eof>')

I can't find the error.  Everything seems to match.  

Not a lua coder.

**Comment by BLavery** [comment]
Hello,
You need to have added your own wifi passwords, obviously.
I need to see your exact file init2-WIFI.lua. Post it or email it. I'll
look at it.

Brian

**Comment by kskenyon** [comment]
local APlist = {
    {"MOTO4C8A", "c*******"}, 
    {"netis_2.4G_E7D2C0", "z********"}
}
-- or simply APlist = { "ap", "pw" }

-- wifi.sta.disconnect()   -- uncommect to FORCE connection attempts from the APlist

if #APlist == 2 and APlist[1][1] == nil then APlist = {APlist} end  -- if simple mode, reformat correctly

local station_cfg={}

-- Connect to my wifi
local function connecting()
    local apnum = 1  -- start with first AP listed
    station_cfg.ssid=APlist[1][1]
    station_cfg.pwd=APlist[1][2]
    station_cfg.save=true
    wifi.sta.config(station_cfg)
    print("Connecting to AP " .. station_cfg.ssid  .. " ...")

    tmr.alarm(0, 500, 1, function()
        if wifi.sta.getip()~=nil then
          tmr.stop(1)
          tmr.stop(0)
          print("Connected: " .. wifi.sta.getip())
          if not Time then node.task.post( function() station_cfg=nil dofile("init3-TIME.lua")  end) end
        end
    end)

    tmr.alarm(1, 30000, 1, function()  -- if not connecting after 30 secs, cycle to next AP in list
        if #APlist > 1 then
            apnum = apnum+1
            if apnum > #APlist then apnum = 1 end
            station_cfg.ssid=APlist[apnum][1]
            station_cfg.pwd=APlist[apnum][2]
            wifi.sta.config(station_cfg)
            print("Trying AP " .. station_cfg.ssid .. " ...")
        else
            print("Still trying to connect ...")
        end
    end)
end


if wifi.sta.getip()~=nil then
      -- easy: from prev credentials, it has autoconnected.  We did nothing!
      local ssid = wifi.sta.getconfig()
      print ("Auto-connected "  .. wifi.sta.getip(), ssid)
      if not Time then node.task.post( function() dofile("init3-TIME.lua")  end) end
else
      connecting() -- Not autoconnected, so we need formal connection process
end

-- Note that "normally", any later wifi disconnect (once first connected) will auto-reconnect as available,
--    but only to the earlier used AP, not to any of the alternatives.
-- It is legitimate to "RE"-load this file later, to rescan all AP credentials.
--    Then it's just for wifi resetting, 
--    IE, Doesn't go on again to time & proj sequence on reconnect. Those are already loaded.
-- But there is nothing automatic about invoking such a reload. A "project"-level possibility only.


The error indicates a missing end to the local function connecting().  I can’t find what’s wrong.  

I’m using a fresh firmware from nodemcu-build with everything you require.

I like your esuite-lua idea.  

Kevin

**Comment by BLavery** [comment]
Kevin,

Hmmm
That lua code looks correct.
Let me clutch at some straws!

How about you reload ALL the files to the 8266.  And you could look
carefully at the WIFI file as actually on the 8266 using RELOAD at right
column, then RIGHTCLICK on the WIFI file and "View" it. It's a  low-grade
way to view file contents, but at least it shows exactly what code sits on
the 8266.

You do have the next file loaded? the TIME file?
And you have put a valid project file at top line of init.lua?
And the project file is loaded to 8266 also?
Ie the minimum startup is 4 files: init, WIFI, TIME, projectfile.

You could try just a single AP credentials in your wifi setup.  And watch
that one with underscores. I seem to recall some funny effects long ago
related to such.

Lastly, can you find someone else's SIMPLE wifi startup, to see if that can
get a wifi connection, and that your 8266 itself is OK?  I often use a port
scanner (like AngryIP) on PC or Android APP (like fing) to see wifi logins,
or wifi.sta.getip() on the 8266 (after a couple of seconds to do the login).

And then I am running out of ideas to try. Keep me posted either way.

Brian

**Comment by kskenyon** [comment]
Got it sorted.  Had to start WIFI with a short dedicated lua then that stuck for future cfg use so this code is mostly bypassed now.  Everything has to be done exactly right for esuite-lua to work. No surprises there.  WIFI code in some older on-line postings has been deprecated.  Only very recent will work with latest <master> firmware.

**Comment by BLavery** [comment]
Oh great.

And yes, wifi syntax had changed recently. Just something to catch you out!

Thanks for trying e-suite. I hope it serves you well.

And meantime I will try to replicate your issue so that I can see what
might have caused your problems. I don't like unexplained issues.

Cheers
Brian

**Comment by kskenyon** [comment]
I finally got everything sorted.  

Starting WIFI with a working simple file set the IP so it didn’t need to try again. I don’t think init2-WIFI.lua has to do anything now.

Running project16.lua successfully.

Thanks for the help.  Your code is fine, my understanding of esuite wasn’t.  Documentation is good for an experienced weenie, not so good for a noob to nodemcu and lua like me.  How about a youtube video?

Kevin

**Comment by BLavery** [comment]
Well you picked a more complex project. MQTT.
But Youtube? I hate youtube. I'm  a documentation man. <g>

**Comment by kskenyon** [comment]
But your audience is adult learners.  I started with Fortran in 1969, went threw the C/PM, BASIC and DOS years and then got busy raising kids.  I have time to tinker again. Having fun.  Know your audience.  :-)  Youtube is much easier to follow than documentation to get started.  Your project has a lot of moving parts to get in line.  

Again, thanks for releasing it to the world.

Kevin
